[package]
name = "remoc-obs"
version = "0.4.4"
edition = "2021"
authors = ["Sebastian Urban <surban@surban.net>"]
readme = "README.md"
repository = "https://github.com/surban/remoc-obs/"
documentation = "https://docs.rs/remoc-obs"
rust-version = "1.58"
description = "Collections (Vec, HashMap, HashSet, append-only list) that can be observed and mirrored remotely."
keywords = ["remote", "observable", "collections", "remoc"]
categories = ["asynchronous", "network-programming"]
license = "Apache-2.0"

[dependencies]
futures = "0.3"
tokio = { version = "1.0", features = ["sync"] }
serde = { version = "1.0", features = ["derive"] }
remoc = { version = "0.9.14", default-features = false, features = ["rch"] }
tracing = "0.1"

[dev-dependencies]
remoc = { version = "0.9.11", default-features = false, features = [
    "default-codec-json",
] }
