[package]
name = "rpc_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
remoc = {path="../remoc"}
tokio = "1"
serde = { version = "1", features = ["derive"] }
